esphome:
  name: perfume-genie-esp8266
  friendly_name: Perfume Genie ESP8266
  comment: Perfume Genie 2.0 ESP8266.

esp8266:
  board: esp_wroom_02

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3CUKZWjezC26eaJjQzDoVUgW9Di8FyUcFlWwnNnPbvw="

ota:
  - platform: esphome
    password: !secret my_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
   - light.turn_on:
      id: status_led
      brightness: 100%
      red: 0%
      green: 0%
      blue: 100%
  on_disconnect:
   - light.turn_on:
      id: status_led
      brightness: 100%
      red: 100%
      green: 0%
      blue: 0%

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Perfume-Genie-Esp8266"
    password: "12345678"

captive_portal:

# Get time from ha
time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
# WIFI Status  
  - platform: status
    name: "Wifi Status"
    icon: "mdi:wifi" 

# Rear button fan toggle
  - platform: gpio
    name: Genie button
    icon: "mdi:gesture-tap-button"
    internal: true
    pin:
      number: 3
      inverted: true
      mode:
        input: true
        pullup: true
    on_click:
      then:
      - fan.toggle:
          id: fan_toggle

# Fan section
output:                                                                                                                                                                         
  - platform: esp8266_pwm
    id: fan_speed
    pin: 4
                                                                                                                                                                  
    frequency: "25000 Hz"
                                                                                                                                                                  
    min_power: 0%
    max_power: 100%

fan:
  - platform: speed
    output: fan_speed
    name: "Perfume Genie Fan"
    id: fan_toggle  
    speed_count: 4
    on_turn_off:
    - light.turn_on:
        id: status_led
        brightness: 100%
        red: 0%
        green: 0%
        blue: 100%
    on_turn_on:
    - light.turn_on:
        id: status_led
        brightness: 100%
        red: 0%
        green: 100%
        blue: 0%

# Fan section END

# Status LED
light:
  - platform: neopixelbus
    name: status_leds
    id: status_led
    variant: WS2812
    pin: 15
    num_leds: 1
    type: GRB
    internal: true

    
